
# TODO: 画像ファイルのURLを、RasPiが撮影した画像に切り替える。
room_config:
  '1F':
    floor: 1
    room_name: '休憩エリア'
    free_space_img: '/images/0/cameras/0.png'
  '2F':
    floor: 2
    room_name: 'ROSE cafe'
    inside_img: '/images/2/cameras/0.png'
    counter_img: '/images/2/cameras/1.png'
    ticket_counter_img: '/images/1/cameras/0.png'
  '3F-A':
    floor: 3
    room_name: 'スエヒロ'
    inside_img: '/images/4/cameras/0.png'
    counter_img: '/images/4/cameras/1.png'
    ticket_counter_img: '/images/3/cameras/0.png'
  '3F-B':
    floor: 3
    room_name: ''
    inside_img: '/images/5/cameras/0.png'
    counter_img: '/images/5/cameras/1.png'
    ticket_counter_img: '/images/3/cameras/0.png'
  '4F-C':
    floor: 4
    room_name: 'C食堂'
    inside_img: '/images/7/cameras/0.png'
    inside2_img: '/images/7/cameras/1.png'
    counter_img: '/images/7/cameras/2.png'
    ticket_counter_img: '/images/6/cameras/0.png'
  '4F-D':
    floor: 4
    room_name: 'D食堂'
    inside_img: '/images/8/cameras/0.png'
    inside2_img: '/images/8/cameras/1.png'


senders:
  ##############################
  # 1階
  '0':  # 休憩エリアに設置する
    secret: 'sender_secret'
    cameras:
      '0':
        location: '休憩エリア'
  ##############################
  # 2階
  '1':  # 2階券売機前に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '2階券売機前'
  '2':  # 2階食堂内部に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '食堂'
      '1':
        location: 'カウンター前'
  ##############################
  # 3階
  '3':  # 3階券売機前に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '3階券売機前'
  '4':  # A食堂内部に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '食堂'
      '1':
        location: 'カウンター前'
  '5':  # B食堂内部に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '食堂'
      '1':
        location: 'カウンター前'
  ##############################
  # 4階
  '6':  # 4階券売機前に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '4階券売機前'
  '7':  # C食堂内部に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '食堂(1)'
      '1':
        location: '食堂(2)'
      '2':
        location: 'カウンター前'
  '8':  # D食堂内部に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '食堂(1)'
      '1':
        location: '食堂(2)'
