
# TODO: 画像ファイルのURLを、RasPiが撮影した画像に切り替える。
room_config:
  '1F':
    floor: 1
    room_name: '休憩エリア'
    free_space_img: '/img/1F_free_space.jpg'
  '2F':
    floor: 2
    room_name: 'ROSE cafe'
    inside_img: '/img/2F_inside.jpg'
    counter_img: '/img/2F_counter.jpg'
    ticket_counter_img: '/img/2F_ticket.jpg'
  '3F-A':
    floor: 3
    room_name: 'スエヒロ'
    inside_img: '/img/3F_A_inside.jpg'
    counter_img: '/img/3F_A_counter.jpg'
    ticket_counter_img: '/img/3F_ticket.jpg'
  '3F-B':
    floor: 3
    room_name: ''
    inside_img: '/img/3F_B_inside.jpg'
    counter_img: '/img/3F_B_counter.jpg'
    ticket_counter_img: '/img/3F_ticket.jpg'
  '4F-C':
    floor: 4
    room_name: 'C食堂'
    inside_img: '/img/4F_C_inside1.jpg'
    inside2_img: '/img/4F_C_inside2.jpg'
    counter_img: '/img/4F_C_counter.jpg'
    ticket_counter_img: '/img/4F_ticket.jpg'
  '4F-D':
    floor: 4
    room_name: 'D食堂'
    inside_img: '/img/4F_D_inside1.jpg'
    inside2_img: '/img/4F_D_inside2.jpg'


senders:
  ##############################
  # 1階
  '0':  # 休憩エリアに設置する
    secret: 'sender_secret'
    cameras:
      '0':
        location: '休憩エリア'
  ##############################
  # 2階
  '1':  # 2階券売機前に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '2階券売機前'
  '2':  # 2階食堂内部に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '食堂'
      '1':
        location: 'カウンター前'
  ##############################
  # 3階
  '3':  # 3階券売機前に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '3階券売機前'
  '4':  # A食堂内部に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '食堂'
      '1':
        location: 'カウンター前'
  '5':  # B食堂内部に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '食堂'
      '1':
        location: 'カウンター前'
  ##############################
  # 4階
  '6':  # 4階券売機前に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '4階券売機前'
  '7':  # C食堂内部に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '食堂(1)'
      '1':
        location: '食堂(2)'
      '2':
        location: 'カウンター前'
  '8':  # D食堂内部に設置
    secret: 'sender_secret'
    cameras:
      '0':
        location: '食堂(1)'
      '1':
        location: '食堂(2)'
